spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  datasource:
    url: jdbc:postgresql://localhost:5432/proj?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
